In [1]:
import numpy as np

In [2]:
s = np.array([33, 64, 50, 45])
s

array([33, 64, 50, 45])

In [3]:
s[2]

50

In [4]:
len(s)

4

In [5]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a + b)
## array([15, 23, 14,  8])
a - b

[15 23 14  8]


array([ 5, -7, -4, -6])

In [6]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c

array([24. ,  9. , 13.6])

In [7]:
a = np.array([120, 150, 190])
b = np.array([130, 130, 130])
x = np.array([2, 3, 2.5])
d = 72
e = x*d

In [8]:
e

array([144., 216., 180.])

In [9]:
c

array([24. ,  9. , 13.6])

In [10]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

In [11]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

102.0

In [12]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [13]:
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [14]:
Hut_Paradise_values = Hut_Paradise_DF.values

In [15]:
x = Hut_Paradise_values[4]

In [16]:
x

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [17]:
y = Hut_Paradise_values[:,3]
y

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [18]:
z = Hut_Paradise_values[:,1] -Hut_Paradise_values[:,5]
z

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [19]:
g = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])

In [20]:
q = g@Hut_Paradise_values[:,4]
q

1348

In [21]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [22]:
f = 2*v + -3*w
f

array([-3, 14,  3,  4,  2])

In [23]:
h = u@f
h

0

In [24]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [25]:
A.shape
## (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])
## a_23= 1 a_32= 3 a_33= 1

a_23= 1 a_32= 3 a_33= 1


In [26]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [27]:
matrix = np.array( [ Husband_Income , Wife_Income , Mother_In_Law_Income ] )

matrix.T

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [28]:
cons = np.array( [ Husband_Consumption , Wife_Consumption , Mother_In_Law_Consumption ] )
cons.T

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [29]:
inc = matrix.T * 0.87

In [30]:
inc

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [31]:
p = inc - cons.T
p

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [32]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [33]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [34]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [35]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [36]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

In [37]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [38]:
Z = A@x
Z

array([26, 30])

In [39]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [40]:
A

array([[1, 9, 8, 5],
       [3, 6, 3, 2],
       [3, 3, 3, 3],
       [0, 2, 5, 9],
       [4, 4, 1, 2]])

In [41]:
B

array([[ 1, -1,  0,  1,  1],
       [-2,  0,  2, -1,  1]])

In [42]:
Z=np.dot(B,A)

In [43]:
Z

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [44]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A = np.array([x,y,z])
A

array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [45]:
G = A.T@A
G

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [46]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [47]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [48]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [49]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [50]:
P = Price_DF.values
C = Count_DF.values
salon_inc = (P*C)@(com)
print(salon_inc)

[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [51]:
P = Price_DF.values
C = Count_DF.values
styl_inc = (P*C)@(np.ones(5)-com)
print(styl_inc)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


In [52]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [53]:
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [54]:
B = A@np.linalg.inv(A)

In [55]:
import numpy as np
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))

-2.9999999999999982


In [56]:
A = np.matrix ("2, 0, 0; 0, 1, 0 ; 0, 0, 4")
print(np.linalg.det(A))

7.999999999999998


In [57]:
print(np.linalg.det(np.linalg.inv(A)))

0.12500000000000003


In [58]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

2


In [59]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,10,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

3


In [60]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [61]:
A_inv=np.linalg.inv(A)

In [62]:
A_inv

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [63]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [64]:
A = np.array([v1, v2, v3, v4]).T
print(np.linalg.matrix_rank(A))

4


In [65]:
A

array([[ 9,  2,  4,  3],
       [10,  0,  0, -4],
       [ 7,  5,  0,  3],
       [ 7,  1,  4, -1],
       [ 9,  4,  1, -4]])

In [66]:
G = A.T@A
G

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [67]:
print(np.linalg.det(G))

3716647.9999999995


In [68]:
G_inv=np.linalg.inv(G)
G_inv

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [69]:
A = np.array([[1, 1], [1, 2]])

In [70]:
A

array([[1, 1],
       [1, 2]])

In [71]:
G = A.T@A
G

array([[2, 3],
       [3, 5]])

In [72]:
v1 = np.array([2, 10, -2])
v2 = np.array([3, 2, -2])
v3 = np.array([8, 14, -6])
A = np.array([v1, v2, v3]).T

In [73]:
print(np.linalg.matrix_rank(A))

2
